### ISSUE TITLE
:sloth: Feature request > Interactive xc (TUI)

### ISSUE THREAD

**Issue by adriens** [joerdav/xc#102]
# :grey_question: About

Being able to run/discover tasks in an interactive way can be very convenient.

Today, we can run `xc` to get the list of available tasks.

:point_right: The purpose of this tasks is to offer a new (and cool :nerd_face: ) way to achieve this.

# :dart: Feature request

The main idea would to offer a cool TUI user experience on top of `xc` with the following [_Charm_ tools](https://github.com/charmbracelet)

- [bubbles](https://github.com/charmbracelet/bubbles)
- [lipgloss](https://github.com/charmbracelet/lipgloss)
- [gum](https://github.com/charmbracelet/gum)

At this end, we could run : 

`xc --interactive`
`xc -i`

... and land on the following kind of user experience (eg. interactively list/run tasks):

![68747470733a2f2f73747566662e636861726d2e73682f67756d2f64656d6f2e676966](https://github.com/joerdav/xc/assets/5235127/8b8db62a-1eb0-4104-b0bd-82bcbee7eec2)

**Comment by joerdav** [comment]
Thanks for the suggestion, so far I've been using fzf for this purpose, but agree a flag might be nice for this.

If you're curious here's my zshrc alias for fzf and xc:
```sh
x() {
  xc $(xc -s |  fzf --preview 'xc -d {} | glow --style dark')
}
```

The ` | glow --style dark` part is optional, but adds color to the preview.

**Comment by a-h** [comment]
I would love this too.

As an MVP, if I could type `xc`, see the list of tasks, move up/down to select, and hit enter to run, that would be great.

If there's missing params or something, in the MVP it wouldn't work at all, and that would be fine.

I could use an alias, but I often run xc inside a bash shell created by `nix develop`, or via `nix shell github:joerdav/xc` etc. so my zsh aliases from my user profile aren't copied thorugh.

**Comment by joerdav** [comment]
That's a good point actually, it could be the default behaviour of `xc`.

I think the Pick list bubble should suffice: https://github.com/charmbracelet/bubbles#list

I recently added telescope support for xc too when I migrated from fzf to telescope: https://github.com/joerdav/telescope-xc.nvim

**Comment by adriens** [comment]
The neovim plugon looks really cool :sunglasses:

**Comment by joerdav** [comment]
I had a crack at this, seems to work well. However, one issue is tasks with inputs.

**Comment by a-h** [comment]
I can't see it on a branch, can I try it out?

**Comment by joerdav** [comment]
Yes sorry! Just pushed it to the branch `interactive`

**Comment by joerdav** [comment]
Planning on a merge, I just need to update docs etc. Inputs can be thought about later.
