### ISSUE TITLE
Missing trailing line in markdown file results in duplicated requirements

### ISSUE THREAD

**Issue by JokerQyou** [joerdav/xc#124]
Paste the following content into `test.md`:

<pre>
### A

```
echo AAA
```

### B

```
echo BBB
```

### C

Requires: A, B
</pre>

Be sure to make the `Requires: A, B` line the last line of the file.

Then run `xc -f test.md -d C` to view task `C`, it would show:

```shell
$ xc -f test.md -d C
## C

Requires: A, B, A, B
RunDeps: sync

Run: always
```

Adding an empty line to the end of the markdown file would resolve this. But I think this is a bug of `xc`, as missing an empty line at the end is not an issue in markdown syntax.

Version was `v0.8.4` installed into go version `1.21.6`.

**Comment by joerdav** [comment]
I've pushed what I believe to be a fix. Please install `v0.8.5`
