### ISSUE TITLE
Feature request: concurrent tasks

### ISSUE THREAD

**Issue by a-h** [joerdav/xc#126]
I have an app that needs to run a background database, but I also want to run the frontend.

At the moment, with `xc`, I open up multiple tabs in tmux, and run each command. However, I end up with a lot of tabs.

Imagine if `xc` supported concurrent tasks...

````
## Tasks

### run-db

```bash
pocketbase serve
```

### run-app

```bash
npm run dev
```

### run

parallel: run-db, run-app
````

In this design, you could run `xc run` and it would run `run-db` and `run-app` in parallel. The app might start before the db, but really, your app should handle that.

Alternatively, `requires` could be updated to have some tags after the other tasks. That way you can run a setup task, then start some parallel tasks.

````
## Tasks

### run-db

```bash
pocketbase serve
```

### run-app

requires: delete-db, run-db [parallel]

```bash
npm run dev
```
````

Maybe this is all a bit too much for `xc`, and this is best done in `air` or similar, just an idea based on how I've been using it.

**Comment by joerdav** [comment]
Hey, 

There is a feature for this already with a slight different design than what you have proposed.

Please see https://xcfile.dev/task-syntax/run-deps/

I'm not quite happy with the current design, but I don't want to break people depending on it.

Your example would be written as:

````md
## Tasks

### run-db

```bash
pocketbase serve
```

### run-app

```bash
npm run dev
```

### run

runDeps: async

requires: run-db, run-app
````
