### ISSUE TITLE
Support for multiple shells(os specific)

### ISSUE THREAD

**Issue by LVladymyr** [joerdav/xc#41]
Right now it is not possible to use runner in different OS, but it would be so nice to have this options. It could be implemented throw OS/shell specific comment or any other way.

**Comment by joerdav** [comment]
@LVladymyr Thanks for the feedback. xc is shipped with a bash interpreter, so should work across operating systems, even if you don't have a shell environment.

Though, this means that certain shell `coreutils` won't work, like `cp`.

There is an issue on the interpeter that xc depends on which would resolve this: https://github.com/mvdan/sh/issues/93
