### ISSUE TITLE
Configurable 'tasks' heading?

### ISSUE THREAD

**Issue by foundrytom** [joerdav/xc#49]
Love the idea of `xc`. Thank you. I'm coming at this from a slightly different angle, is there any appetite for making the name of the tasks header configurable?

I would really like to use `xc` to check that the examples in our docs work. Being able to use "Examples" as the header instead of "Tasks" means the docs would still make sense for the reader.

**Comment by joerdav** [comment]
Happy to accept this feature, I assume a flag would be fit for purpose?

I'd been thinking about how this tool could be useful in different languages, and this would help towards that!

**Comment by foundrytom** [comment]
> Happy to accept this feature, I assume a flag would be fit for purpose?

Awesome, thanks. Yeah I guess something like `-h --heading <string>`?
