### ISSUE TITLE
feature request / idea: interactive menu

### ISSUE THREAD

**Issue by a-h** [joerdav/xc#5]
From Vim, it would be great if you could hit, `leader t` or something, to list xc tasks and run one.

So you'd press `leader t`, then `1`, `2` etc. to run that task, or escape to quit.

```
:map <leader>t :!xc build<cr>
```

Unfortunately, interactive commands produce a mess of escape codes in Vim.

<img width="1123" alt="Screenshot 2022-01-29 at 14 07 39" src="https://user-images.githubusercontent.com/1029947/151664119-7ef8aa29-8bc5-4b5f-8a42-dd53d0307547.png">

However, something like https://github.com/christoomey/vim-run-interactive would need to be used to provide the interactivity of the picklist.

**Comment by joe-davidson1802** [comment]
I agree this would be really valuable. I've added a temporary solution for now by exposing 2 new options you can use fzf to provide this. 

f2d8bec

Here's how to use it:
https://github.com/joe-davidson1802/xc#vim-usage

I'll keep this issue open until I create a vim plugin to do this, and make sure all cases are covered.

**Comment by waldyrious** [comment]
It looks like the Vim usage docs introduced in f2d8bec were later removed in commit 377b957 from #9. Was that intentional, or perhaps an overlook?

**Comment by joerdav** [comment]
@waldyrious good spot, this wasn't intentional, I intended to move it. I think it would fit well in a new docs page "IDE Support" or something similar. What do you think?

**Comment by waldyrious** [comment]
Yeah, sounds good to me. I don't use Vim myself, so I'll leave it to others to contribute that page :)

**Comment by joerdav** [comment]
This capability was documented with 97f60c47e08577f76d340728729147ea0f6d1288

**Comment by waldyrious** [comment]
> I'll keep this issue open until I create a vim plugin to do this, and make sure all cases are covered.

Just to be sure, did you change your mind on that goal?
