### ISSUE TITLE
Support short/long option aliases

### ISSUE THREAD

**Issue by waldyrious** [joerdav/xc#56]
Most options of the CLI have both a short and a long version. Notable exceptions are `-version`, which only has a long version, and `-y`, which only has a short one. For consistency, these two could have both variants.

Here's what I'd suggest:

- `-V` as the short variant of `-version` (since -v is [often used](http://www.catb.org/~esr/writings/taoup/html/ch10s05.html#id2949649) for `--verbose`)
- `-noprompt` as the long variant of `-y`

Additionally, perhaps consider changing `-md` to `-n`/`-dry-run`, since the format of the task definition document should not be relevant — i.e., it should be possible to eventually make `xc` support AsciiDoc, reStructuredText, and other lightweight markup formats.

**Comment by joerdav** [comment]
Agree there is a bit of inconsistency. I think usually there is short form for commonly used flags, so may not be applicable for all. But I definitely agree this could be improved.

**Comment by waldyrious** [comment]
Sure, thanks! I've submitted #65 for additional consistency in the option descriptions.

By the way, do you have any thoughts about the suggestion I made above to make xc support formats other than markdown? I could create a separate issue to track that if it's something you'd consider.

**Comment by waldyrious** [comment]
Cool, makes sense. I've opened #66 to track that.
