### ISSUE TITLE
:pray:  feature request > auto complete

### ISSUE THREAD

**Issue by adriens** [joerdav/xc#71]
it would be awesome so, like in `make` to be able to autocomplete (`TAB`) `xc` targets :pray:

**Comment by joerdav** [comment]
Released in `v0.2.0` plus docs are at https://xcfile.dev/getting-started/#install-completion

**Comment by adriens** [comment]
<pre><font color="#5FD700">❯</font> xc -V
xc version: 0.2.0
<font color="#5FD700">❯</font> xc -complete
<span style="background-color:#D3D7CF"><font color="#080808">  </font></span><span style="background-color:#3465A4"><font color="#D3D7CF"></font></span><span style="background-color:#3465A4"><font color="#E4E4E4">  </font></span><span style="background-color:#3465A4"><font color="#EEEEEE"><b>~</b></font></span><span style="background-color:#3465A4"><font color="#E4E4E4">/Github/</font></span><span style="background-color:#3465A4"><font color="#EEEEEE"><b>odata-eaux-baignade-noumea</b></font></span><span style="background-color:#3465A4"><font color="#E4E4E4"> </font></span><span style="background-color:#4E9A06"><font color="#3465A4"></font></span><span style="background-color:#4E9A06"><font color="#2E3436">   main </font></span><font color="#4E9A06"></font> xc                                                                                                                                                                  <font color="#2E3436"></font><span style="background-color:#2E3436"><font color="#4E9A06"> ✔ </font></span><span style="background-color:#2E3436"><font color="#D3D7CF"></font></span><span style="background-color:#D3D7CF"><font color="#2E3436"> 08:05:30  </font></span>
<font color="#729FCF"><b>data</b></font>/      README.md
</pre>


Still this works : 

<pre><font color="#FF0000">❯</font> xc
    latest   Print the latest status of all beaches
    last-20  Print the 20 last status of all beaches
             
<font color="#5FD700">❯</font> xc latest
+ sh /tmp/sh-interp-6edf2c088f4c1fc1 +duckdb.org duckdb
+ curl https://tea.xyz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13734  100 13734    0     0  10364      0  0:00:01  0:00:01 --:--:-- 10365

┌──────────────────────────────────────┬────────────┬────────────┐
│                plage                 │ flag_color │ flag_color │
│               varchar                │  varchar   │  varchar   │
├──────────────────────────────────────┼────────────┼────────────┤
│ Plage de la promenade Pierre-Vernier │ BLUE       │ 🟦         │
│ Plage de l&apos;Anse-Vata                 │ BLUE       │ 🟦         │
│ Plage de Magenta                     │ BLUE       │ 🟦         │
│ Plage du Kuendu Beach                │ BLUE       │ 🟦         │
│ Plage de la baie des Citrons         │ BLUE       │ 🟦         │
└──────────────────────────────────────┴────────────┴────────────┘
<span style="background-color:#D3D7CF"><font color="#080808">  </font></span><span style="background-color:#3465A4"><font color="#D3D7CF"></font></span><span style="background-color:#3465A4"><font color="#E4E4E4">  </font></span><span style="background-color:#3465A4"><font color="#EEEEEE"><b>~</b></font></span><span style="background-color:#3465A4"><font color="#E4E4E4">/Github/</font></span><span style="background-color:#3465A4"><font color="#EEEEEE"><b>odata-eaux-baignade-noumea</b></font></span><span style="background-color:#3465A4"><font color="#E4E4E4"> </font></span><span style="background-color:#4E9A06"><font color="#3465A4"></font></span><span style="background-color:#4E9A06"><font color="#2E3436">   main </font></span><font color="#4E9A06"></font></pre>


:information_source:  I'm running on `zsh` (`OMZ`)

**Comment by joerdav** [comment]
@adriens I believe you might be missunderstanding the commands.

`xc -complete` will install xc auto completion to zsh.

You should be running the commands as (<tab> is where you press the tab key):

```sh
❯ xc -V
xc version: 0.2.0
❯ xc -complete
❯ xc <tab>
latest      last-20
```

You only have to install completion once, then you won't have to run it again.

**Comment by adriens** [comment]
:ok_hand: 

https://user-images.githubusercontent.com/5235127/226893050-58948756-ba74-49bf-a862-40f9658c15f2.mp4
