### ISSUE TITLE
Include a demo gif of xc being used in command line

### ISSUE THREAD

**Issue by adriens** [joerdav/xc#79]
https://github.com/charmbracelet/vhs

:information_source: I can make one for you and PR the code and webm, gif & mp4 if you want to

**Comment by joerdav** [comment]
What do you think this would illustrate, and where would it live? I have a recording of the vscode capabilities on the homepage already. 

If you think there's something a new user could benefit from in a text demo then I'm open to contributions.

**Comment by adriens** [comment]
Hmmm, I was thinkg about a pure terminal demo.

I could use your README's tasks as a base for that.
