### ISSUE TITLE
Add adriens tutorial on xc to the docs site

### ISSUE THREAD

**Issue by adriens** [joerdav/xc#94]
https://dev.to/adriens/runnable-readmes-w-xc-1c6d

![image](https://github.com/joerdav/xc/assets/5235127/cc8a5b7f-0e62-4d53-bedd-93b0d41bfa00)

**Comment by joerdav** [comment]
Thanks! I will add this to the docs site.

**Comment by adriens** [comment]
I'll show it to my team as I think we'll adopt it on enterprise projects.
Please feel free to close the issue as soon as you want to keep the repo clean :nerd_face:
