### ISSUE TITLE
:name_badge: Please provide a ready-to-use md badge :memo: 

### ISSUE THREAD

**Issue by adriens** [joerdav/xc#96]
# :grey_question: About

We tend to use `xc` on vairous projects and I would like peple to be aware that the reposiotry  uses `xc` to describe various available tasks.

:point_right: Providing a badge would help a lot :sloth: 

# :dart: Feature request

- [ ] **Provide a ready to use `markdown` badge** we could copy/paste on top of our `README.md` 
- [ ] **Make it clickable s**o it makes people land to https://xcfile.dev/

# :moneybag: Benefits

- No need to tell people what the README is capable of... nor how to use it :sloth:

**Comment by joerdav** [comment]
This is a brilliant idea, I have been trying to think of ways to signpost a readme as xc ready, for discoverability reasons as well as so we can easily track uptake in open source!

**Comment by joerdav** [comment]
I hope this is what you had in mind: https://xcfile.dev/getting-started/#let-people-know-you-use-xc

**Comment by adriens** [comment]
> I hope this is what you had in mind: https://xcfile.dev/getting-started/#let-people-know-you-use-xc

Sure it is 🤩 
![image](https://github.com/joerdav/xc/assets/5235127/81bc617a-46ae-454c-8925-e733b9281da2)

**Comment by adriens** [comment]
- https://github.com/adriens/auptitcafe-data/pull/8

**Comment by adriens** [comment]
![image](https://github.com/joerdav/xc/assets/5235127/ed7b96f5-9837-4208-9a00-25c46e295528)

**Comment by adriens** [comment]
Nice shot and thanks a lot for feedback 🙏
